import pyautogui
import time

pyautogui.hotkey("win","e")
time.sleep(5)
pyautogui.click(x=336, y=61)
pyautogui.write(r"E:\TeraBoxDownload\CorelDRAW Graphics Suite 2022 v24.0.0.301\CorelDRAW Graphics Suite 2022 v24.0.0.301\Crack")
pyautogui.press("enter")
time.sleep(2)
pyautogui.hotkey("ctrl","a")
time.sleep(1)
pyautogui.hotkey("ctrl","c")
time.sleep(1)
pyautogui.click(x=1356, y=59)
pyautogui.write(r"C:\Program Files\Corel\CorelDRAW Graphics Suite 2022\Programs64")
pyautogui.press("enter")
time.sleep(2)
pyautogui.hotkey("ctrl","v")
time.sleep(2)
pyautogui.press("enter")
time.sleep(2)
pyautogui.click(x=770, y=416)
time.sleep(2)
pyautogui.click(x=901, y=445)